### ISSUE TITLE
no glitches but scan dash obliged and more

### ISSUE THREAD

**Issue by Sheetah73** [etaylor8086/prime-randomizer-web#2]
Mode: Standard
Logic: No glitch
Artifacts: Random
Difficulty: normal
Seed: 43214083
Version: 1.00

Layout Descriptor:  A4I5UdUkbyB7Xbl-LuybQCPa8foSkwFxIefCZnR31qB2y3QEkSEmrnV8fhQZCrpEEomJUqK9zRr3gvGGiZ08qFg

Description of problem:
impossible to get the good item without making some "glitch" f.e : scan Dash
Spoiler log (if available):
{
	"info": {
		"mode": "standard",
		"logic": "no-glitches",
		"artifacts": "randomized",
		"difficulty": "normal",
		"seed": 43214083,
		"version": "0.2.0"
	},
	"locations": {
		"Tallon Overworld": {
			"Landing Site": "Missile Expansion",
			"Alcove": "Energy Tank",
			"Frigate Crash Site": "Energy Tank",
			"Overgrown Cavern": "Missile Expansion",
			"Root Cave": "Energy Tank",
			"Artifact Temple": "Energy Tank",
			"Transport Tunnel B": "Power Bomb",
			"Arbor Chamber": "Spider Ball",
			"Cargo Freight Lift to Deck Gamma": "Energy Tank",
			"Biohazard Containment": "Missile Expansion",
			"Hydro Access Tunnel": "Missile Expansion",
			"Great Tree Chamber": "Grapple Beam",
			"Life Grove Tunnel": "Charge Beam",
			"Life Grove (Start)": "Missile Expansion",
			"Life Grove (Underwater Spinner)": "Energy Tank"
		},
		"Chozo Ruins": {
			"Main Plaza (Half-Pipe)": "Missile Expansion",
			"Main Plaza (Grapple Ledge)": "Wavebuster",
			"Main Plaza (Tree)": "Missile Expansion",
			"Main Plaza (Locked Door)": "Missile Expansion",
			"Ruined Fountain": "Energy Tank",
			"Ruined Shrine (Beetle Battle)": "X-Ray Visor",
			"Ruined Shrine (Half-Pipe)": "Missile Expansion",
			"Ruined Shrine (Lower Tunnel)": "Artifact of Strength",
			"Vault": "Ice Beam",
			"Training Chamber": "Missile Expansion",
			"Ruined Nursery": "Missile Expansion",
			"Training Chamber Access": "Energy Tank",
			"Magma Pool": "Missile Expansion",
			"Tower of Light": "Artifact of Chozo",
			"Tower Chamber": "Power Bomb Expansion",
			"Ruined Gallery (Missile Wall)": "Missile Expansion",
			"Ruined Gallery (Tunnel)": "Missile Expansion",
			"Transport Access North": "Morph Ball",
			"Gathering Hall": "Gravity Suit",
			"Hive Totem": "Missile Launcher",
			"Sunchamber (Flaahgra)": "Wave Beam",
			"Sunchamber (Ghosts)": "Energy Tank",
			"Watery Hall Access": "Missile Expansion",
			"Watery Hall (Scan Puzzle)": "Missile Expansion",
			"Watery Hall (Underwater)": "Plasma Beam",
			"Dynamo (Lower)": "Artifact of World",
			"Dynamo (Spider Track)": "Ice Spreader",
			"Burn Dome (Tunnel)": "Morph Ball Bomb",
			"Burn Dome (I. Drone)": "Space Jump Boots",
			"Furnace (Spider Tracks)": "Energy Tank",
			"Furnace (Tunnel)": "Energy Tank",
			"Hall of the Elders": "Missile Expansion",
			"Crossway": "Artifact of Spirit",
			"Elder Chamber": "Missile Expansion",
			"Antechamber": "Missile Expansion"
		},
		"Magmoor Caverns": {
			"Lava Lake": "Missile Expansion",
			"Triclops Pit": "Missile Expansion",
			"Storage Cavern": "Missile Expansion",
			"Transport Tunnel A": "Missile Expansion",
			"Warrior Shrine": "Energy Tank",
			"Shore Tunnel": "Power Bomb Expansion",
			"Fiery Shores (Morph Track)": "Missile Expansion",
			"Fiery Shores (Warrior Shrine Tunnel)": "Missile Expansion",
			"Plasma Processing": "Missile Expansion",
			"Magmoor Workstation": "Missile Expansion"
		},
		"Phendrana Drifts": {
			"Phendrana Shorelines (Behind Ice)": "Missile Expansion",
			"Phendrana Shorelines (Spider Track)": "Missile Expansion",
			"Chozo Ice Temple": "Missile Expansion",
			"Ice Ruins West": "Power Bomb Expansion",
			"Ice Ruins East (Behind Ice)": "Missile Expansion",
			"Ice Ruins East (Spider Track)": "Missile Expansion",
			"Chapel of the Elders": "Missile Expansion",
			"Ruined Courtyard": "Artifact of Wild",
			"Phendrana Canyon": "Missile Expansion",
			"Quarantine Cave": "Artifact of Warrior",
			"Research Lab Hydra": "Artifact of Sun",
			"Quarantine Monitor": "Energy Tank",
			"Observatory": "Phazon Suit",
			"Transport Access": "Flamethrower",
			"Control Tower": "Missile Expansion",
			"Research Core": "Missile Expansion",
			"Frost Cave": "Energy Tank",
			"Research Lab Aether (Tank)": "Missile Expansion",
			"Research Lab Aether (Morph Track)": "Missile Expansion",
			"Gravity Chamber (Underwater)": "Artifact of Lifegiver",
			"Gravity Chamber (Grapple Ledge)": "Missile Expansion",
			"Storage Cave": "Missile Expansion",
			"Security Cave": "Thermal Visor"
		},
		"Phazon Mines": {
			"Main Quarry": "Boost Ball",
			"Security Access A": "Missile Expansion",
			"Storage Depot B": "Missile Expansion",
			"Storage Depot A": "Missile Expansion",
			"Elite Research (Phazon Elite)": "Artifact of Truth",
			"Elite Research (Laser)": "Missile Expansion",
			"Elite Control Access": "Artifact of Nature",
			"Ventilation Shaft": "Artifact of Elder",
			"Phazon Processing Center": "Artifact of Newborn",
			"Processing Center Access": "Missile Expansion",
			"Elite Quarters": "Missile Expansion",
			"Central Dynamo": "Varia Suit",
			"Metroid Quarantine B": "Power Bomb Expansion",
			"Metroid Quarantine A": "Missile Expansion",
			"Fungal Hall B": "Missile Expansion",
			"Phazon Mining Tunnel": "Missile Expansion",
			"Fungal Hall Access": "Super Missile"
		}
	}
}

**Comment by etaylor8086** [comment]
Hi there,

Where did you get stuck out of curiosity?

**Comment by etaylor8086** [comment]
Yeah there's definitely a logic bug going on with the Boost Ball, Spider Ball, and Grapple Beam requirements for this seed. Grapple is either Spider or Boost locked in this case, Spider is Grapple locked, and Boost Ball is spider locked. I'll get this fixed as soon as I can.

**Comment by Sheetah73** [comment]
thx a lot, there's no problem you found it well, i'm so impressed that you are that active on your randomizer Good Job man

**Comment by etaylor8086** [comment]
It turned out to be a logic bug with Great Tree Chamber. It wasn't properly checking for Boost Ball and/or Spider ball access. See commit ed5d9bf for more info.

Not only has that been fixed, but the lategame Chozo Ruins/Tallon Overworld locations now factor in access through the Crashed Frigate. This is largely for Antechamber, Great Tree Chamber, and Overgrown Cavern access without Spider Ball.

This fix will be released in v0.2.1 shortly.
