### ISSUE TITLE
Boost Ball into Tunnels?

### ISSUE THREAD

**Issue by WashedUpLinkshot** [etaylor8086/prime-randomizer-web#3]
Are there any plans to add Boost Ball into the logic for tunnels that "expect" Bomb Jumping, and other achievable vertical feats? Doing so would create situations where Bombs are in Deep Chozo but you get early access to Boosting.

**Comment by etaylor8086** [comment]
Actually, yes. On a further note, I'm planning on overhauling the logic system to allow for more granular options, such as skipping certain items in certain regions (i.e. allowing Tower Chamber without gravity, SJ, morph, etc)
