### ISSUE TITLE
Morph Ball is blocked by morph point of no return

### ISSUE THREAD

**Issue by pkmnfrk** [etaylor8086/prime-randomizer-web#5]
Version: 1.0.0-beta.5
Permalink: NTM5MzI1ODM1LDU5WUhBQUFBQVc2
Seed: 539325835
Logic: ?
Mode: ?
Artifacts: yes

Description of problem:
In this seed, Morph Ball is in Alcove (the room behind the ship), and the Space Jump is in the Beetle room (where you normally get Morph Ball). In order to get the Morph Ball, you need to enter a point of no return.

Now, considering your options are limited at this point, one will quickly exhaust alternative locations, but still, I was under the impression that the "No Bombs in 'Point of No Return' Morph Ball tunnels" would prevent this. At the very least, SauceRelic's tracker marks this location as inaccessible.

Spoiler log (if available):
[Prime_NTM5MzI1ODM1LDU5WUhBQUFBQVc2_spoiler.txt](https://github.com/etaylor8086/prime-randomizer-web/files/2564282/Prime_NTM5MzI1ODM1LDU5WUhBQUFBQVc2_spoiler.txt)

**Comment by pkmnfrk** [comment]
Having typed that, I do realize that it says "No Bombs", not "No Morph or Bombs". However, I maintain that it should prevent this, even if on principle.

**Comment by etaylor8086** [comment]
The logic for getting those two items seems sound to me. You enter Ruined Shrine after getting your first set of missiles, fight the beetles, get the Space Jump Boots, and then jump over the half pipe to leave Ruined Shrine. You can then get to Alcove by going to Landing Site and double jumping off of Samus's ship.

**Comment by etaylor8086** [comment]
Hi @pkmnfrk, is there anything else I need to follow up with on this issue?

**Comment by pkmnfrk** [comment]
Sorry, didn't see the first reply.

The problem is that if you don't know that the beetles have the Space Jump, you won't go there because you might get soft locked. It's similar to the option to not have beams in the vanilla beam rooms; yes, if the beams are placed there you're cool, but if they're not, you're stuck.

Yes, this is at the beginning of the game, but it can suck to lose a bunch of time on a run because you either A) have to try it anyway, or B) run around to literally every other accessible spot to rule it out.

**Comment by etaylor8086** [comment]
This has been fixed; Ruined Shrine, Frost Cave, and the three vanilla beam rooms (Chapel of the Elders, Antechamber, Elder Chamber) are no longer required to enter as a "point of no return" location if Obfuscate Items is checked. It will be available in the next update when it gets pushed.

@pkmnfrk, sorry for the confusion on my part. Thanks again for reporting this!
